Repository lazybytez/custom-eggs, pull requests merged in 2020-09, with the labels that each got.

#5 Add .editorconfig
  .editorconfig
Labels: C3 - enhancement

#3 Nginx php-fpm Egg
  .github/MEDIA/DockerImagePterodactyl.PNG
  README.md
  eggs/nginx-fpm/README.md
  eggs/nginx-fpm/image/Dockerfile
  eggs/nginx-fpm/image/entrypoint.sh
  eggs/nginx-fpm/image/nginx.conf.tpl
  eggs/nginx-fpm/image/php-fpm.conf.tpl
  eggs/nginx-fpm/image/startup.sh
  eggs/nginx-fpm/image/supervisord.conf
  eggs/nginx-fpm/nginx-fpm.json
  eggs/nginx/nginx.json
Labels: C2 - feature

#7 Fix readme links
  README.md
Labels: C3 - enhancement

#9 First egg release
  .editorconfig
  .github/MEDIA/DockerImagePterodactyl.PNG
  README.md
  eggs/nginx-fpm/README.md
  eggs/nginx-fpm/image/Dockerfile
  eggs/nginx-fpm/image/entrypoint.sh
  eggs/nginx-fpm/image/nginx.conf.tpl
  eggs/nginx-fpm/image/php-fpm.conf.tpl
  eggs/nginx-fpm/image/startup.sh
  eggs/nginx-fpm/image/supervisord.conf
  eggs/nginx-fpm/nginx-fpm.json
Labels: S9 - release

#10 Update rebaser.yml
  .github/workflows/rebaser.yml
Labels: S9 - release

#11 Refactor pubic => public
  eggs/nginx-fpm/nginx-fpm.json
Labels: C1 - bug

#12 Fix typo in nginx-fpm
  eggs/nginx-fpm/nginx-fpm.json
Labels: S9 - release
