Repository lazybytez/custom-eggs, pull requests merged in 2021-07, with the labels that each got.

#19 Create a Grafana Image Renderer egg
  README.md
  eggs/grafana-image-renderer/README.md
  eggs/grafana-image-renderer/config.json
  eggs/grafana-image-renderer/egg-grafana-image-renderer.json
  eggs/grafana-image-renderer/image/Dockerfile
  eggs/grafana-image-renderer/image/entrypoint.sh
Labels: C2 - feature

#20 Merge develop into master
  README.md
  eggs/grafana-image-renderer/README.md
  eggs/grafana-image-renderer/config.json
  eggs/grafana-image-renderer/egg-grafana-image-renderer.json
  eggs/grafana-image-renderer/image/Dockerfile
  eggs/grafana-image-renderer/image/entrypoint.sh
Labels: S9 - release

#21 Update the repository to a newer state
  .github/labels.js
  .github/workflows/git.yml
  .github/workflows/rebaser.yml
  .github/workflows/stale.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
  commitlint.config.js
  eggs/grafana-image-renderer/egg-grafana-image-renderer.json
Labels: C3 - enhancement

#22 Create a Caddy egg
  eggs/caddy/README.md
  eggs/caddy/caddy.json
  eggs/caddy/egg-caddy.json
  eggs/grafana-image-renderer/README.md
Labels: C2 - feature

#23 Remove the NGINX egg
  README.md
  eggs/nginx-fpm/README.md
  eggs/nginx-fpm/image/Dockerfile
  eggs/nginx-fpm/image/entrypoint.sh
  eggs/nginx-fpm/image/nginx.conf.tpl
  eggs/nginx-fpm/image/php-fpm.conf.tpl
  eggs/nginx-fpm/image/startup.sh
  eggs/nginx-fpm/image/supervisord.conf
  eggs/nginx-fpm/nginx-fpm.json
Labels: C3 - enhancement

#24 Update readme for webserver specific software
  README.md
Labels: C4 - documentation

#25 Create a MariaDB egg with automated certificate generation
  README.md
  eggs/mariadb-openssl/README.md
  eggs/mariadb-openssl/egg-maria-d-b-with-open-s-s-l.json
  eggs/mariadb-openssl/install.my.cnf
  eggs/mariadb-openssl/my.cnf
Labels: C2 - feature

#26 Adjust the core README and Caddy README
  README.md
  eggs/caddy/README.md
Labels: C4 - documentation

#29 Change installer image to yolks alpine image for GIR
  eggs/grafana-image-renderer/egg-grafana-image-renderer.json
Labels: C3 - enhancement

#28 Switch to yolks alpine image for Caddy
  eggs/caddy/egg-caddy.json
Labels: C3 - enhancement
